// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.example.grpc;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string messages = 1;</code>
   */
  java.util.List<java.lang.String>
      getMessagesList();
  /**
   * <code>repeated string messages = 1;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated string messages = 1;</code>
   */
  java.lang.String getMessages(int index);
  /**
   * <code>repeated string messages = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessagesBytes(int index);
}
